# Available commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0x00494d64 width=5.0',
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = false
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change'
]

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        35
outer.right =      10

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# alt-slash = 'layout tiles horizontal vertical'
# alt-comma = 'layout accordion horizontal vertical'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Switch to workspace using hyper + number  
cmd-alt-ctrl-shift-1 = 'workspace 1'
cmd-alt-ctrl-shift-2 = 'workspace 2'
cmd-alt-ctrl-shift-3 = 'workspace 3'
cmd-alt-ctrl-shift-4 = 'workspace 4'
cmd-alt-ctrl-shift-5 = 'workspace 5'
cmd-alt-ctrl-shift-6 = 'workspace 6'
cmd-alt-ctrl-shift-7 = 'workspace 7'
cmd-alt-ctrl-shift-8 = 'workspace 8'
cmd-alt-ctrl-shift-h = 'workspace prev'
cmd-alt-ctrl-shift-l = 'workspace next'
cmd-alt-ctrl-shift-n = 'layout floating tiling'

# Move window to workspace using meh + number
ctrl-shift-alt-1 = 'move-node-to-workspace 1'
ctrl-shift-alt-2 = 'move-node-to-workspace 2'
ctrl-shift-alt-3 = 'move-node-to-workspace 3'
ctrl-shift-alt-4 = 'move-node-to-workspace 4'
ctrl-shift-alt-5 = 'move-node-to-workspace 5'
ctrl-shift-alt-6 = 'move-node-to-workspace 6'
ctrl-shift-alt-7 = 'move-node-to-workspace 7'
ctrl-shift-alt-8 = 'move-node-to-workspace 8'

# Move and focus window to workspace using "ultra" + number
cmd-alt-ctrl-1 = ['move-node-to-workspace 1', 'workspace 1']
cmd-alt-ctrl-2 = ['move-node-to-workspace 2', 'workspace 2']
cmd-alt-ctrl-3 = ['move-node-to-workspace 3', 'workspace 3']
cmd-alt-ctrl-4 = ['move-node-to-workspace 4', 'workspace 4']
cmd-alt-ctrl-5 = ['move-node-to-workspace 5', 'workspace 5']
cmd-alt-ctrl-6 = ['move-node-to-workspace 6', 'workspace 6']
cmd-alt-ctrl-7 = ['move-node-to-workspace 7', 'workspace 7']
cmd-alt-ctrl-8 = ['move-node-to-workspace 8', 'workspace 8']

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
# alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# 'service' binding mode declaration.
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']

[workspace-to-monitor-force-assignment]
    1 = 1 
    2 = 1
    3 = 1
    4 = 1
    5 = 1
    6 = 2
    7 = 2
    8 = 2

# App specific config

[[on-window-detected]]
    if.app-name-regex-substring = 'Brave Browser'
    run = ['move-node-to-workspace 1']

[[on-window-detected]]
    if.app-id = 'com.mitchellh.ghostty'
    run = ['move-node-to-workspace 2']

[[on-window-detected]]
    if.app-name-regex-substring = 'Cursor'
    run = ['move-node-to-workspace 3']

[[on-window-detected]]
    if.app-name-regex-substring = 'Slack'
    run = ['move-node-to-workspace 4']
