#!/usr/bin/env bash

# Colors for scannable output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "🔍 Auditing dotfile ignore boundaries..."
echo "----------------------------------------"

# A list of absolute paths that SHOULD be tracked
should_track=(
  "$HOME/.gitignore"
  "$HOME/.gitmodules"
  "$HOME/.gitconfig"
  "$HOME/Brewfile.core"
  "$HOME/Brewfile.mantis"
  "$HOME/Brewfile.mando"
  "$HOME/.scripts/bootstrap.sh"
  "$HOME/.scripts/install-dotfiles.sh"
  "$HOME/.scripts/seed-zoxide.sh"
  "$HOME/.scripts/wt"
  "$HOME/.claude/CLAUDE.md"
  "$HOME/.claude/skills/test_skill/SKILL.md"
  "$HOME/.config/aerospace/aerospace.toml"
  "$HOME/.config/aerospace/nested/subfolder/test.toml"
  "$HOME/.config/iterm2/default_profile.json"
  "$HOME/.config/nvim/init.lua"
  "$HOME/.config/nvim/lua/plugins/example.lua"
  "$HOME/.config/kitty/kitty.conf"
  "$HOME/.config/mise/config.toml"
  "$HOME/.config/zsh/configs/post/99-mise.zsh"
  "$HOME/.scripts/install-vscode-extensions.sh"
  "$HOME/.scripts/validate_config_ignore.sh"
  "$HOME/.zshrc"
  "$HOME/.gitmux.conf"
  "$HOME/.config/git/ignore"
  "$HOME/.config/sesh/sesh.toml"
  "$HOME/.config/tmux/tmux.conf"
  "$HOME/.config/tmux/scripts/new-helper.sh"
  "$HOME/.config/tmux/scripts/prune-history.sh"
  "$HOME/.config/zsh/commands.txt"
  "$HOME/.config/zsh/functions/aws"
  "$HOME/.config/karabiner/karabiner.json"
  "$HOME/.espanso/match/base.yml"
  "$HOME/.config/nushell/config.nu"
  "$HOME/.config/gh/config.yml"
  "$HOME/.code_profiles/jsdev/data/User/settings.json"
  "$HOME/.code_profiles/jsdev/data/User/keybindings.json"
  "$HOME/.code_profiles/jsdev/data/User/snippets/js.json"
  "$HOME/.code_profiles/newprofile/ext/extensions.json"
)

# A list of absolute paths that SHOULD be blocked by your * rules
should_ignore=(
  "$HOME/Downloads/movie.mp4"
  "$HOME/Documents/tax_returns.pdf"
  "$HOME/.claude/secret_api_key.txt"
  "$HOME/.config/iterm2/random_autogenerated_file.txt"
  "$HOME/.config/some_new_app/config.json"
  "$HOME/.config/mise/config.local.toml"
  "$HOME/.zshrc.local"
  "$HOME/.config/machine-name"
  "$HOME/.config/tmux/plugins/tpm/tpm"
  "$HOME/.config/tmux/themes/catppuccin/catppuccin.tmux"
  "$HOME/.config/anthropic/credentials/default.json"
  "$HOME/.config/gcloud/credentials.db"
  "$HOME/.config/xdash/ssh_host_key"
  "$HOME/.config/cursor/plans/some.plan.md"
  "$HOME/.claude/skills/synced/some-skill/SKILL.md"
  "$HOME/.claude/skills/.trash/123-abc/some-skill/SKILL.md"
  "$HOME/.config/zsh/.DS_Store"
  "$HOME/Brewfile.local"
  "$HOME/.config/nushell/history.txt"
  "$HOME/.config/nushell/history.sqlite3"
  "$HOME/.config/karabiner/automatic_backups/karabiner_20250211.json"
  "$HOME/Brewfile"
  "$HOME/.aliases"
  "$HOME/.commands.local"
  "$HOME/.zsh_history"
  "$HOME/.code_profiles/jsdev/ext/svelte.svelte-vscode-109.1.0/package.json"
  "$HOME/.code_profiles/pydev/data/logs/20230101/main.log"
  "$HOME/.code_profiles/pydev/data/CachedExtensionVSIXs/ms-python.python"
  "$HOME/.code_profiles/pydev/data/machineid"
  "$HOME/.code_profiles/nsdev/data/User/globalStorage/state.vscdb"
)

errors=0

# --no-index tests the ignore rules themselves. Without it, check-ignore skips
# files that are already tracked and reports them as "not ignored" even when the
# rules would block them (so new files next to them would be silently ignored).

# Test the files that SHOULD be tracked
for file in "${should_track[@]}"; do
  # check-ignore returns 0 if ignored, 1 if NOT ignored
  /usr/bin/git --git-dir="$HOME/.cfg/" --work-tree="$HOME" check-ignore -q --no-index "$file"
  if [ $? -eq 0 ]; then
    echo -e "${RED}✗ FAIL:${NC} File should be tracked but is ignored -> $file"
    errors=$((errors + 1))
  else
    echo -e "${GREEN}✓ PASS:${NC} Properly tracked -> $file"
  fi
done

# Test the files that SHOULD be ignored
for file in "${should_ignore[@]}"; do
  /usr/bin/git --git-dir="$HOME/.cfg/" --work-tree="$HOME" check-ignore -q --no-index "$file"
  if [ $? -eq 1 ]; then
    echo -e "${RED}✗ FAIL:${NC} File should be ignored but is TRACKED -> $file"
    errors=$((errors + 1))
  else
    echo -e "${GREEN}✓ PASS:${NC} Properly isolated -> $file"
  fi
done

echo "----------------------------------------"
if [ $errors -eq 0 ]; then
  echo -e "${GREEN}🚀 Perfect setup! No ignore violations detected.${NC}"
  exit 0
else
  echo -e "${RED}⚠️ Found $errors ignore configuration errors.${NC}"
  exit 1
fi
