#!/usr/bin/env bash

# Colors for scannable output
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "🔍 Auditing dotfile ignore boundaries..."
echo "----------------------------------------"

# A list of absolute paths that SHOULD be tracked
should_track=(
  "$HOME/.gitignore"
  "$HOME/.gitconfig"
  "$HOME/Brewfile"
  "$HOME/.claude/skills/test_skill/SKILL.md"
  "$HOME/.config/aerospace/aerospace.toml"
  "$HOME/.config/aerospace/nested/subfolder/test.toml"
  "$HOME/.config/iterm2/default_profile.json"
  "$HOME/.config/nvim/init.lua"
  "$HOME/.config/nvim/lua/plugins/example.lua"
  "$HOME/.scripts/install-vscode-extensions.sh"
)

# A list of absolute paths that SHOULD be blocked by your * rules
should_ignore=(
  "$HOME/Downloads/movie.mp4"
  "$HOME/Documents/tax_returns.pdf"
  "$HOME/.claude/secret_api_key.txt"
  "$HOME/.config/iterm2/random_autogenerated_file.txt"
  "$HOME/.config/some_new_app/config.json"
)

errors=0

# Test the files that SHOULD be tracked
for file in "${should_track[@]}"; do
  # check-ignore returns 0 if ignored, 1 if NOT ignored
  /usr/bin/git --git-dir="$HOME/.cfg/" --work-tree="$HOME" check-ignore -q "$file"
  if [ $? -eq 0 ]; then
    echo -e "${RED}✗ FAIL:${NC} File should be tracked but is ignored -> $file"
    errors=$((errors + 1))
  else
    echo -e "${GREEN}✓ PASS:${NC} Properly tracked -> $file"
  fi
done

# Test the files that SHOULD be ignored
for file in "${should_ignore[@]}"; do
  /usr/bin/git --git-dir="$HOME/.cfg/" --work-tree="$HOME" check-ignore -q "$file"
  if [ $? -eq 1 ]; then
    echo -e "${RED}✗ FAIL:${NC} File should be ignored but is TRACKED -> $file"
    errors=$((errors + 1))
  else
    echo -e "${GREEN}✓ PASS:${NC} Properly isolated -> $file"
  fi
done

echo "----------------------------------------"
if [ $errors -eq 0 ]; then
  echo -e "${GREEN}🚀 Perfect setup! No ignore violations detected.${NC}"
  exit 0
else
  echo -e "${RED}⚠️ Found $errors ignore configuration errors.${NC}"
  exit 1
fi
